# SPDX-FileCopyrightText: The migadu-client.go Authors
# SPDX-License-Identifier: 0BSD

version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    assignees:
      - sebhoss
